connection/urls.py
from django.urls import path
from django.views.generic import TemplateView
import connection.views as views

app_name = 'connection'

urlpatterns = [
    path('', TemplateView.as_view(template_name='connection/type_select.html'), name='type_select'),
    path('<str:type>/create', views.connection_create, name='create'),
    path('<int:pk>/', views.connection_detail, name='detail'),
    path('<int:pk>/clear', views.tables_clear, name='tables_clear'),
    path('<int:pk>/delete', views.connection_delete, name='delete'),
    path('<int:pk>/update', views.connection_update, name='update'),
    path('table/<int:pk>/', views.loaded_tables, name='loaded_tables'),
    path('table/<int:pk>/add', views.table_add, name='table_add'),
    path('table/<int:pk>/~add', views.table_sql_add, name='table_sql_add'),
    path('table/<int:pk>/detail', views.table_detail, name='table_detail'),
    path('table/<int:pk>/delete', views.table_delete, name='table_delete'),

]

datavis/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.views import login
from django.urls import path
from django.views import defaults as default_views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from graphene_django.views import GraphQLView
from users.views import user_home_view


class PrivateGraphQLView(LoginRequiredMixin, GraphQLView):
    pass


urlpatterns = [
    path('', user_home_view, name='user_home'),
    path('home/', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # path('admin/', admin.site.urls),  # set a honeypot on this
    path(settings.ADMIN_URL, admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('connection/', include('connection.urls', namespace='connection')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('package/', include('package.urls', namespace='package')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    url(
        regex=r'^$',
        view=views.user_list_view,
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # path('<str:username>/charts/', views.UserChartListView.as_view(), name='charts'),
]

connection/forms.py
from django import forms
from django.forms.models import modelform_factory
from django.forms.widgets import PasswordInput

from .models import Connection, Table


def connection_form(type):
    if type == 'externaldb':
        fields = ("type", "username", "password", "port", "hostname", "name")
    elif type == 'flatfile':
        fields = ("type", "name", "path")
    elif type == 'remote':
        fields = ("username", "password", "port", "hostname", "name")
    else:
        raise Exception("type not correct")

    return modelform_factory(model=Connection, fields=fields, widgets={"password": PasswordInput})


class LoadedTablesForm(forms.Form):
    table = forms.ChoiceField(choices=(), required=True)

    def __init__(self, tables, *args, **kwargs):
        super(LoadedTablesForm, self).__init__(*args, **kwargs)
        self.fields['table'].choices = list(zip(tables, tables))


class AvailableTablesForm(LoadedTablesForm):
    primary_key_column = forms.CharField(max_length=255, required=False)
    add_id = forms.BooleanField(label="Has no id field", required=False)


class SQLForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ('name', 'primary_key_column', 'query')
        widgets = {'query': forms.Textarea}


class ConnectionForm(forms.ModelForm):
    class Meta:
        model = Connection
        exclude = ('password',)

connection/views.py
import blaze as bz
from odo import odo

from subprocess import Popen

from django.contrib import messages
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.text import slugify
# from graphene_django.views import GraphQLView

from .app_settings import MEDIA_URL, MEDIA_ROOT, RAW_DB_URL
from .forms import AvailableTablesForm, connection_form, LoadedTablesForm, SQLForm
from .models import Connection, Table
from .tasks import create_periodic_task, commit_table
from .terms_and_conditions import connection_terms
from .utils import create_notebook, delete_table, delete_tables, make_db_table_name, tables_loaded


# confluent start kafka

@login_required
def connection_create(request, type):
    form = connection_form(type)(request.POST or None, request.FILES)
    if form.is_valid():
        con = form.save(commit=False)
        con.user = request.user
        if type == 'remote':
            con.type = 'rfile'
        if con.connection_status == 1:
            con.is_valid = True
        con.save()
        messages.success(request, 'Database connection was successfully added')
        return redirect(con)
    else:
        form = connection_form(type)
    return render(request, "connection/create.html", {'form': form, 'type': type, 'terms': connection_terms})


@login_required
def connection_update(request, pk):
    con = get_object_or_404(Connection, pk=pk)
    # the types we use in the create view are different. if it's none of csv, excel and rfile
    # then we assume it must be one of the external db types
    type = {'csv': 'flatfile', 'excel': 'flatfile', 'rfile': 'remote'}.get(con.type, 'externaldb')

    form = connection_form(type)(request.POST or None, request.FILES, instance=con)
    if form.is_valid():
        con = form.save(commit=False)
        if con.connection_status:
            con.is_valid = True
            msg = "Database connection was successfully updated"
        else:
            con.is_valid = False
            msg = "Database connection updated but a connection couldn't be established"
        con.save()
        messages.success(request, msg)
        return redirect(con)
    else:
        form = connection_form(type)(instance=con)
    return render(request, "connection/update.html", {"form": form, "con": con})


@login_required
def connection_delete(request, pk):
    con = Connection.objects.get(pk=pk)
    if request.user == con.user or request.user.is_staff:
        delete_tables(pk)
        con.delete()
        messages.success(request, "Database Connection removed")
        return redirect('connection:list')
    else:
        messages.warning(request, 'Access denied')
        return redirect(request.user)


@login_required
def connection_detail(request, pk):
    con = get_object_or_404(Connection, pk=pk)

    if request.user == con.user or request.user.is_staff:
        loaded_tbs = tables_loaded(con).keys()
        available_tbs = sorted(set(con.table_names) - loaded_tbs)

        context = {'con': con, 'sqlform': SQLForm(),
                   'loaded_tables_form': LoadedTablesForm(sorted(loaded_tbs)),
                   'unloaded_tables_form': AvailableTablesForm(available_tbs)}
        return render(request, 'connection/detail.html', context)
    else:
        messages.warning(request, 'Access denied')
        return redirect(request.user)


@login_required
def loaded_tables(request, pk):
    # TODO: could we make this view just a function
    con = get_object_or_404(Connection, pk=pk)
    loaded_tbs = tables_loaded(con)

    form = LoadedTablesForm(sorted(loaded_tbs.keys()), request.POST or None)
    if form.is_valid():
        table = form.cleaned_data['table']
        table_pk = loaded_tbs[table]
        if 'details' in request.POST:
            return redirect('connection:table_detail', table_pk)

        elif 'remove' in request.POST:
            return redirect('connection:table_delete', table_pk)

        elif 'clear' in request.POST:
            return redirect('connection:tables_clear', pk)

        elif 'load+' in request.POST:
            table_name = form.cleaned_data['table']
            name = make_db_table_name(con, table_name)
            tb = Table.objects.get(source_db=con, name=name)

            if tb.state == 'cleaned':
                create_periodic_task(tb.pk, name)
                messages.info(request, f"Consuming new data from {table_name}.")
            else:
                messages.warning(request, "Cannot send data to warehouse at the moment. Data from this connection yet "
                                          "to be cleaned")
            return redirect(con)

        elif 'chart_create' in request.POST:
            return redirect('chart:create', table_pk)

        elif 'analyse' in request.POST:
            from .utils import extract_jupyter_url

            # Notebook server closes after 5 minutes of inactivity
            Popen(['nohup', 'jupyter-notebook', MEDIA_ROOT + con.user.username + '/notebooks/'],
            # Popen(['nohup', 'jupyter-notebook', 'user_notebooks/' + con.user.username],
                  stdout=open('/dev/null', 'w'),
                  stderr=open('jupyter_stderr.log', 'a'))

            # TODO: we need to terminate the notebooks after completion
            # pid = p.id  # we can use this to terminate it from other locations
            # p.terminate()
            # TODO: if so many users are trying to analyse tables, the url might not point to the correct one
            url = extract_jupyter_url('jupyter_stderr.log')
            messages.info(request, f"Navigate to '{url}' and use the password provided by your administrator")
            return redirect(con)
    else:
        return redirect('connection:detail', pk)


@login_required
def table_add(request, pk):
    con = get_object_or_404(Connection, pk=pk)
    loaded_tbs = tables_loaded(con)
    available_tbs = sorted(set(con.table_names) - loaded_tbs.keys())

    form = AvailableTablesForm(available_tbs, request.POST or None)
    if form.is_valid():
        table_name = form.cleaned_data['table']
        pk_column = form.cleaned_data.get('primary_key_column') or 'id'

        # TODO: a signal could be used for this in the model, so that, we just pass in the raw name to the table model
        name = make_db_table_name(con, table_name)

        tb = Table.objects.create(source_db=con, name=name, primary_key_column=pk_column)
        create_notebook(con.user.username, name)
        commit_table.delay(tb.pk, RAW_DB_URL)
        messages.info(request, f"Loading from {table_name}!")
        return redirect(con)
    else:
        return redirect('connection:detail', pk)


@login_required
def tables_clear(request, pk):
    """Clear loaded tables from connection
    """
    con = Connection.objects.filter(pk=pk).first()

    if (con.user == request.user) or request.user.is_staff:
        delete_tables(pk)
        messages.success(request, 'Tables cleared')
        return redirect(con)

    else:
        messages.warning(request, 'Access denied')
        return redirect(request.user)


@login_required
def table_delete(request, pk):
    tb = get_object_or_404(Table, pk=pk)
    if (tb.source_db.user == request.user) or request.user.is_staff:
        delete_table(tb)
        messages.success(request, f'{tb.just_name} removed')
        con = get_object_or_404(Connection, pk=tb.source_db_id)
        return redirect(con)
    else:
        messages.warning(request, 'Access denied')
        return redirect(request.user)


@login_required
def table_detail(request, pk):
    tb = get_object_or_404(Table, pk=pk)
    if (tb.source_db.user == request.user) or request.user.is_staff:
        table_html = tb.to_html
        prefix = tb.source_db.user.username + '_' + tb.source_db.name + '__'
        name = tb.name.replace(prefix, '')
        template = 'connection/table_detail.html'
        return render(request, template, {'name': name, 'tb': tb, 'table_html': table_html})
    else:
        messages.warning(request, 'Access denied')
        return redirect(request.user)


# @login_required
# def table_update(request, pk):
#     tb = get_object_or_404(Table, pk)
#     form = TableIdFieldForm(tb.columns, request.POST or None)
#     if form.is_valid():
#         tb.primary_key_column = form.cleaned_data['primary_key_column']
#         tb.save()
#         return redirect(tb.source_db)
#     else:
#         return render(request, '', {'form': TableIdFieldForm(tb.columns)})


@login_required
def table_sql_add(request, pk):
    # TODO: this field is very experimental
    con = get_object_or_404(Connection, pk=pk)
    form = SQLForm(request.POST or None)
    if form.is_valid():
        # TODO: we need some serious pre-processing of this sql statement to avoid anything malicious
        # TODO: .get('') or something
        query = form.cleaned_data.get('query')
        pk_column = form.cleaned_data.get('primary_key_column')
        table_name = slugify(form.cleaned_data['name']).replace('-', '_')
        name = make_db_table_name(con, table_name)

        tb = Table.objects.create(source_db=con, name=name, primary_key_column=pk_column, query=query)
        create_notebook(con.user.username, name)
        commit_table.delay(tb.pk, RAW_DB_URL)
        messages.info(request, f"Loading from {table_name}!")

        return redirect(con)
    else:
        return redirect('connection:detail', pk)

templates/connection/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Add Connection{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Add Connection</li>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Add a data source connection </h1>

    <div class="container">
        <form class="form-horizontal col-md-4 offset-md-3" action="{% url 'connection:create' type %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <a class="btn btn-outline-primary"  data-toggle="modal" data-target="#tncModal">Add</a>

{#            #}
<div class="modal fade" id="tncModal" tabindex="-1" role="dialog" aria-labelledby="tncModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tncModalLabel">Terms and Conditions</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        {{ terms|safe }}
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <input type="submit" class="btn btn-outline-primary" value="Add">
      </div>
    </div>
  </div>
</div>
{#            #}

        </form>
    </div>
</div>



{% endblock %}

templates/connection/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/card_style.css' %}">
{% endblock %}

{% block title %}Connection Detail {% endblock %}

{% block breadcrumb %}
{#    <li class="breadcrumb-item">#}
{#      <a href="{% url 'connection:list' %}">Connection List</a>#}
{#    </li>#}
    <li class="breadcrumb-item active">Connection detail</li>
{% endblock %}


{% block content %}
<div class="row">

    <div class="row col-8">
        <div class=" col-md-6">
            <div class="card border-primary mb-3">
              <div class="card-header">Connection: {{ con.name }}</div>
              <div class="card-body">
              {% with con.type as type %}
                <ul class="card-text">
                    <li>type: {{ type }}</li>
                {% if type != 'csv' and type != 'excel' and type != 'sqlite' %}
                    <li>username: {{ con.username }}</li>
                    <li>hostname: {{ con.hostname }}</li>
                    <li>port: {{ con.port }}</li>
                {% endif %}
                    {% if con.is_valid %}
                        <li><span style="color: blue">database connection validated</span></li>
                    {% else %}
                        <li><span style="color: red">database connection is invalid</span></li>
                    {% endif %}
                    <li>Added on: {{ con.timestamp }}</li>
                    <li>Modified on: {{ con.updated }}</li>
                </ul>
              {% endwith %}
                <a class="btn btn-outline-primary" href="{% url 'connection:update' con.pk %}" role="button">Edit</a>
              </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card border-primary mb-3">
              <div class="card-header">Available Tables</div>
              <div class="card-body">
                <form class="card-text" method="post" action="{% url 'connection:table_add' con.id %}">
                    {% csrf_token %}
                    {{ unloaded_tables_form|crispy }}
                    <input type="submit" name="load" value="Load" class="btn btn-outline-primary">
                </form>
              </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card border-primary mb-3">
              <div class="card-header">Loaded Tables</div>
              <div class="card-body">
                <form class="card-text" method="post" action="{% url 'connection:loaded_tables' con.id %}">
                    {% csrf_token %}
                    {{ loaded_tables_form|crispy }}

                    <div class="btn-group" role="group" aria-label="">
                        <input type="submit" name="details" value="Details" class="btn btn-outline-primary">
                        <input type="submit" name="remove" value="Remove" class="btn btn-outline-danger">
                        <input type="submit" name="clear" value="Clear" class="btn btn-outline-danger">
                    </div>
                    {% if request.user.is_staff %}
                        <hr>
                        <div class="btn-group" role="group" aria-label="">
                            <input type="submit" name="analyse" value="Analyse" class="btn btn-outline-success">
                            <input type="submit" name="load+" value="Load+" class="btn btn-outline-success">
                            <input type="submit" name="chart_create" value="Add Chart" class="btn btn-outline-success">
                        </div>
                    {% endif %}
                </form>
              </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card border-primary mb-3">
          <div class="card-header">Manual table selection    *EXPERIMENTAL</div>
          <div class="card-body">
            <form class="card-text" method="post" action="{% url 'connection:table_sql_add' con.id %}">
                {% csrf_token %}
                {{ sqlform|crispy }}
                <input type="submit" value="Execute" class="btn btn-outline-success">
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

templates/connection/table_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/datatables-responsive/css/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'connection:detail' tb.source_db_id %}">Connection detail</a>
  </li>
  <li class="breadcrumb-item active">Output</li>
{% endblock %}

{% block content %}

{% if table_html is None %}
    Something went wrong
{% else %}
    <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> {{ name|capfirst }} table {% if request.user.is_staff %}in {{ tb.state }}DB{% endif %}
        </div>
        <div class="card-body">
           <div class="table-responsive">
               {{ table_html|safe }}
           </div>
        </div>
    </div>
{% endif %}

{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'vendor/datatables-responsive/js/dataTables.responsive.js' %}"></script>
    <script src="{% static 'js/sb-admin-datatables.min.js' %} "></script>
{% endblock %}

templates/connection/type_select.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block css %}
{#    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">#}
{#    <link rel='stylesheet prefetch'  href="{% static 'vendor/animate/animate.min.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/card_style.css' %}">
{% endblock %}

{% block title %}Select Database Source Type{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Select Database Source Type</li>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <article class="card animated fadeInUp">
        <div class="card-header bg-transparent">
          <h4 class="card-title">Database</h4>
          <h6 class="text-muted">...</h6>
        </div>
        <img class="img-fluid" src="{% static 'img/externaldb.png' %}" alt="Externaldb" style="height: 15em;"/>
        <div class="card-body">
          <p class="card-text">blah blah blah
          </p>
        </div>
        <div class="card-footer text-center bg-transparent">
          <div class="btn-group hidden-sm-down hidden-md-down" role="group" aria-label="Card buttons">
            <a href="{% url 'connection:create' 'externaldb' %}" class="btn btn-outline-primary">Add</a>
            <a href="#" class="btn btn-outline-primary">Read more</a>
          </div>
        </div>
      </article>
    </div>

    <div class="col-xs-12 col-md-4">
      <article class="card animated fadeInUp">
        <div class="card-header bg-transparent">
          <h4 class="card-title">Upload a database</h4>
          <h6 class="text-muted">...</h6>
        </div>
        <img class="img-fluid" src="{% static 'img/flatfile.png' %}" alt="Flat files" style="height: 15em;"/>
        <div class="card-body">
          <p class="card-text">blah blah blah
          </p>
        </div>
        <div class="card-footer text-center bg-transparent">
          <div class="btn-group hidden-sm-down hidden-md-down" role="group" aria-label="Card buttons">
            <a href="{% url 'connection:create' 'flatfile' %}" class="btn btn-outline-primary">Add</a>
            <a href="#" class="btn btn-outline-primary">Read more</a>
          </div>
        </div>
      </article>
    </div>

    <div class="col-xs-12 col-md-4">
      <article class="card animated fadeInUp">
        <div class="card-header bg-transparent">
          <h4 class="card-title">Remote file,log etc.</h4>
          <h6 class="text-muted">...</h6>
        </div>
        <img class="img-fluid" src="{% static 'img/flatfile.png' %}" alt="Remote File"  style="height: 15em;"/>
        <div class="card-body">
          <p class="card-text">Coming soon
          </p>
        </div>
        <div class="card-footer text-center bg-transparent">
          <div class="btn-group hidden-sm-down hidden-md-down" role="group" aria-label="Card buttons">
            <a href="{% url 'connection:create' 'remote' %}" class="btn btn-outline-primary">Add</a>
            <a href="#" class="btn btn-outline-primary">Read more</a>
          </div>
        </div>
      </article>
    </div>

  </div>
</div>

<hr>

{% endblock %}

templates/connection/update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}{{ con.name }}{% endblock %}

{% block content %}
    <div class="container">
      <h1>Connection: {{ con.name }}</h1>
      <form class="form-horizontal col-md-4 offset-md-3" method="post" action="{% url 'connection:update' con.pk %}"
            enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-primary" value="Update">
      </form>
    </div>
{% endblock %}