dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.DashboardView.as_view(), name="home"),
    path('<int:pk>/create', views.chart_create, name='create'),
    path('<int:pk>/delete', views.chart_delete, name='delete'),
    path('<int:pk>/detail', views.chart_detail, name='detail'),
    path('<int:pk>/live', views.live_chart, name='live'),
    path('<int:pk>/update', views.chart_update, name='update'),
    path('<int:con_pk>/list', views.connection_chart_list, name='connection_chart_list'),
    path('<str:username>/list', views.user_chart_list, name='user_chart_list'),
    path('dash', views.Dashboard2View.as_view(), name="dash"),
    path('timeline/', views.TimelineView.as_view(), name="timeline"),
]

datavis/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.views import login
from django.urls import path
from django.views import defaults as default_views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from graphene_django.views import GraphQLView
from users.views import user_home_view


class PrivateGraphQLView(LoginRequiredMixin, GraphQLView):
    pass


urlpatterns = [
    path('', user_home_view, name='user_home'),
    path('home/', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # path('admin/', admin.site.urls),  # set a honeypot on this
    path(settings.ADMIN_URL, admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('connection/', include('connection.urls', namespace='connection')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('package/', include('package.urls', namespace='package')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    url(
        regex=r'^$',
        view=views.user_list_view,
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # path('<str:username>/charts/', views.UserChartListView.as_view(), name='charts'),
]

dashboard/models.py
from ast import literal_eval
from blaze import transform

from django.db import models
from django.shortcuts import reverse

from connection.models import Table
from metric.models import KPI
from users.models import Organisation, User

from .utils import ChartAugment

# TODO: this app should eventually be called dashboard

TYPE_CHOICES = (
    ('area', 'Area'),
    ('bar', 'Bar'),
    ('bubble', 'Bubble'),
    ('doughnut', 'Doughnut'),
    ('line', 'Line'),
    ('pie', 'Pie'),
    ('polarArea', 'Polar Area'),
    ('scatter', 'Scatter'),
    ('radar', 'Radar')
)
FREQUENCY_CHOICES = (
    ('hourly', 'Hourly'),
    ('daily', 'Daily'),
    ('weekly', 'Weekly'),
    ('monthly', 'Monthly'),
    ('quarterly', 'Quarterly'),
    ('annually', 'Annually'),
)
UNIT_CHOICES = (
    ('raw', 'Raw value'),
    ('percent', 'Percentage'),
)


class Chart(models.Model):
    owner = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    # name = models.CharField(max_length=255)
    type = models.CharField(max_length=9, choices=TYPE_CHOICES, default='area')
    kpi = models.ForeignKey(KPI, on_delete=models.CASCADE)
    objective = models.CharField(max_length=255, help_text='What does the chosen kpi intend to achieve?')
    target_value = models.FloatField(help_text="Target value of chosen kpi.")
    unit = models.CharField(max_length=10, choices=UNIT_CHOICES)
    # TODO: is this the same thing as what we have in the package? i.e how frequent to update the chart
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    # TODO: this may be time, etc
    column_x = models.CharField(max_length=255, verbose_name='Column for x-axis')
    kpi_column_variables = models.CharField(max_length=255, verbose_name='Dictionary of kpi variables and column names')
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('updated',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dashboard:detail', kwargs={'pk': self.pk})

    # @property
    # def user(self):
    #     return self.table.source_db.user

    @property
    def variable_mappings(self):
        """
        Map data source columns to kpi variables
        :return:
        """
        return self.kpi.variable_mappings

    def compute(self, data):
        """
        Map data source columns to kpi variables
        :param data: blaze.data object
        :return: computed kpi
        """
        variables = {k: data[v] for k, v in literal_eval(self.kpi_column_variables).items()}
        return self.kpi.compute(variables)

    @property
    def aug(self):
        data = self.table.data

        # TODO: Can we do this out of core?
        # Create new blaze.data object.
        data = transform(data, computed_kpi=self.compute(data))

        # TODO: this has the potential to load everything
        return ChartAugment(self.type, data, self.column_x).augment()

    @property
    def data(self):
        return self.aug['data']

    @property
    def labels(self):
        return self.aug['labels']

    @property
    def name(self):
        return self.kpi.name


class Dashboard(models.Model):
    name = models.CharField(max_length=255)
    charts = models.ManyToManyField(Chart)
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('updated',)

    def __str__(self):
        return self.name

dashboard/forms.py
from django import forms
from connection.models import Table

from .models import Chart


class ChartAddForm(forms.ModelForm):
    class Meta:
        model = Chart
        fields = ('type', 'column_x', 'kpi_column_variables')

    def __init__(self, pk, *args, **kwargs):
        super(ChartAddForm, self).__init__(*args, **kwargs)
        columns = Table.objects.get(pk=pk).columns
        columns = forms.Select(choices=zip(columns, columns))
        self.fields['column_x'].widget = columns
        # self.fields['column_y'].widget = columns

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from connection.models import Connection, Table

from .charts import Plot
from .forms import ChartAddForm
from .models import Chart


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/index.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context.update({'title': "Dashboard"})
        return context


class Dashboard2View(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard2View, self).get_context_data(**kwargs)
        context.update({'title': "Dashboard"})
        return context


class TimelineView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/timeline.html"

    def get_context_data(self, **kwargs):
        context = super(TimelineView, self).get_context_data(**kwargs)
        context.update({'title': "Timeline"})
        return context


@login_required
def chart_create(request, pk):
    table = get_object_or_404(Table, pk=pk)
    user = table.source_db.user
    if request.user == user or request.user.is_staff:

        form = ChartAddForm(pk, request.POST or None)
        context = {'con_pk': table.source_db_id,
                   'form': form,
                   'tb_pk': pk}
        if form.is_valid():
            chart = form.save(commit=False)
            # chart.user = user
            # chart.name = chart.column_x + ' vs ' + chart.column_y
            chart.table = table
            chart.save()
            messages.success(request, 'Chart created')
            return redirect(chart.table.source_db)
        return render(request, 'dashboard/chart_create.html', context)

    else:
        messages.warning(request, "Permission denied")
        redirect(request.user)


@login_required
def user_chart_list(request, username):
    if request.user.username == username or request.user.is_staff:
        charts = Chart.objects.filter(table__source_db__user__username=username)
        return render(request, 'dashboard/chart_list.html', {'charts': charts, 'username': username})
    else:
        messages.warning(request, "Permission denied")
        redirect(request.user)


@login_required
def connection_chart_list(request, con_pk):
    con = get_object_or_404(Connection, pk=con_pk)
    if request.user.username == con.user.username or request.user.is_staff:
        charts = Chart.objects.filter(table__source_db=con)
        return render(request, 'dashboard/chart_list.html', {'charts': charts, 'username': con.user.username})
    else:
        messages.warning(request, "Permission denied")
        redirect(request.user)


@login_required
def chart_detail(request, pk):
    chart = get_object_or_404(Chart, pk=pk)
    if request.user in chart.owner.users.all() or request.user.is_staff:
        updated = chart.updated
        username = chart.owner.name
        chart = Plot(pk)
        return render(request, 'dashboard/chart_detail.html',
                               {'chart': chart, 'updated': updated, 'username': username})
    else:
        messages.warning(request, "Permission denied")
        redirect(request.user)


@login_required
def chart_update(request, pk):
    chart = get_object_or_404(Chart, pk=pk)
    if request.user in chart.owner.users.all() or request.user.is_staff:

        tb_pk = chart.table_id
        con_pk = get_object_or_404(Table, pk=tb_pk).source_db_id
        form = ChartAddForm(tb_pk, request.POST or None, instance=chart)

        context = {"form": form,
                   "pk": pk,
                   "con_pk": con_pk}

        if form.is_valid():
            chart = form.save(commit=False)
            # chart.name = chart.column_x + ' vs ' + chart.column_y
            chart.save()
            messages.success(request, "Chart updated successfully")
            return redirect(chart)
        return render(request, "dashboard/chart_update.html", context)
    else:
        messages.warning(request, "Permission denied")
        redirect(request.user)


@login_required
def chart_delete(request, pk):
    chart = get_object_or_404(Chart, pk=pk)
    if request.user in chart.owner.users.all() or request.user.is_staff:
        chart.delete()
        messages.success(request, "Chart deleted")
        return redirect(chart.table.source_db)
    else:
        messages.warning(request, "Permission denied")
        redirect(request.user)


@login_required
def live_chart(request, pk):
    get_object_or_404(Chart, pk=pk)
    return render(request, 'dashboard/live_chart.html', {'pk': pk})





















# def dashing_dashboard(request, chart_pk):
#     chart_name = get_object_or_404(Chart, pk=chart_pk).name
#     widget = ChartWidget(chart_pk)
#     router.register(widget, chart_name)
#     return



# import requests
#
# url = 'https://api.github.com/graphql'
# json = { "query" : "{ viewer  { login } }" }
# api_token = "your api token here..."
# headers = {'Authorization': 'token %s' % api_token}
#
# r = requests.post(url=url, json=json, headers=headers)
# print (r.text)


# @login_required
# def charts(request, pk):
#     chart = get_object_or_404(Chart, pk=pk)
#     data = chart.table.data[[chart.column_x, chart.column_y]]
#     aug = ChartAugment(chart.type, data, chart.column_x, chart.column_y).augment()
#     print(aug['data'][:4])
#
#     return render(request, 'dashboard/charts/chart_detail1.html', {'data': json.dumps(aug['data'])})


# @login_required
# def plot(request):
#     cs = get_list_or_404(Chart, user=request.user)
#     data = {}
#     for c in cs:
#         df = c.table.data[[c.column_x, c.column_y]]
#         # we need two columns as arrays but this will make them rows and we can easily get separate arrays
#         x, y = df.values.transpose()
#
#         data[c.name] = augment_xy(x, y)
#     return render(request)


# @login_required
# def plot(request, pk):
#     context = {'pk': pk}
#     template = 'dashboard/charts.html'
#     return render(request, template, context)


# class ChartAjaxView(View):
#     def get(self, request, *args, **kwargs):
#         data = {}
#         if request.user.is_staff:
#             qs = '' # Order.objects.all().by_weeks_range(weeks_ago=5, number_of_weeks=5)
#             if request.GET.get('type') == 'chart-1':
#                 # basically trying to get the sales for each day but recompute total sales on each request
#                 days = 7
#                 start_date = timezone.now().today() - datetime.timedelta(days=days-1)
#                 datetime_list = []
#                 labels = []
#                 chart_items = []
#                 for x in range(0, days):
#                     new_time = start_date + datetime.timedelta(days=x)
#                     datetime_list.append(new_time)
#                     labels.append(new_time.strftime("%a"))
#                     new_qs = qs.filter(updated__day=new_time.day, updated__month=new_time.month)
#                     day_total = new_qs.totals_data()['total__sum'] or 0
#                     chart_items.append(day_total)
#
#                 data['labels'] = labels
#                 data['data'] = chart_items
#             if request.GET.get('type') == 'chart-2':
#                 data['labels'] = ["Four Weeks Ago", "Three Weeks Ago", "Two Weeks Ago", "Last Week", "This Week"]
#                 current = 5
#                 data['data'] = []
#                 for i in range(0, 5):
#                     new_qs = qs.by_weeks_range(weeks_ago=current, number_of_weeks=1)
#                     sales_total = new_qs.totals_data()['total__sum'] or 0
#                     data['data'].append(sales_total)
#                     current -= 1
#         return JsonResponse(data)


# class ChartView(LoginRequiredMixin, TemplateView):
#     template_name = 'dashboard/charts/live_chart.html'
#
#     def dispatch(self, *args, **kwargs):
#         user = self.request.user
#         if not user.is_staff:
#             return render(self.request, "400.html", {})
#         return super(ChartView, self).dispatch(*args, **kwargs)
#
#     def get_context_data(self, **kwargs):
#         context = super(ChartView, self).get_context_data(**kwargs)
#         qs = Order.objects.all().by_weeks_range(weeks_ago=10, number_of_weeks=10)
#         start_date = timezone.now().date() - datetime.timedelta(hours=24)
#         end_date = timezone.now().date() + datetime.timedelta(hours=12)
#         today_data = qs.by_range(start_date=start_date, end_date=end_date).get_sales_breakdown()
#         context['today'] = today_data
#         context['this_week'] = qs.by_weeks_range(weeks_ago=1, number_of_weeks=1).get_sales_breakdown()
#         context['last_four_weeks'] = qs.by_weeks_range(weeks_ago=5, number_of_weeks=4).get_sales_breakdown()
#         return context


# @login_required
# def kick(request):
#     exchange = {'2001-01-31': 1.064, '2002-01-31': 1.1305,
#                 '2003-01-31': 0.9417, '2004-01-31': 0.7937,
#                 '2005-01-31': 0.7609, '2006-01-31': 0.827,
#                 '2007-01-31': 0.7692, '2008-01-31': 0.6801,
#                 '2009-01-31': 0.7491, '2010-01-31': 0.7002,
#                 '2011-01-31': 0.7489, '2012-01-31': 0.7755,
#                 '2013-01-31': 0.7531,
#                 }
#
#     browser_stats = [['Chrome', 52.9], ['Firefox', 27.7], ['Opera', 1.6],
#                      ['Internet Explorer', 12.6], ['Safari', 4]]
#
#     temperature = [{u'data': {'2012-00-01 00:00:00 -0700': 7,
#                               '2012-01-01 00:00:00 -0700': 6.9,
#                               '2012-02-01 00:00:00 -0700': 9.5,
#                               '2012-03-01 00:00:00 -0700': 14.5,

templates/dashboard/chart_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}Add Chart{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
      <a href="#">Connection List</a>
    </li>
    <li class="breadcrumb-item active">
      <a href="{% url 'connection:detail' con_pk %}">Connection Detail</a>
    </li>
    <li class="breadcrumb-item active">Add Chart</li>
{% endblock %}


{% block content %}
    <div class="container">
        <form class="form-horizontal col-md-4 offset-md-3" method="post" action="{% url 'dashboard:create' tb_pk %}">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-outline-primary" value="Add">
        </form>
    </div>
{% endblock %}

templates/dashboard/chart_detail.html
{% extends 'base.html' %}
{% load jchart %}
{% load static %}

{% block javascript %}
    <script src="{% static 'node_modules/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'node_modules/@coreui/plugin-chartjs-custom-tooltips/dist/js/custom-tooltips.min.js' %}"></script>
   {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item">
{#    TODO: user_chart_list is not accurate, we also need connection_chart_list#}
    <a href="{% url 'dashboard:user_chart_list' request.user.username %}">Configure Charts</a>
  </li>
  <li class="breadcrumb-item active">Chart Detail</li>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-lg-8">
        <div class="card border-danger" >
          <div class="card-body">
            {{ chart.as_html }}
          </div>
          <div class="card-footer text-white text-center bg-dark border-danger">
            updated at {{ updated|timesince }}
          </div>
        </div>
    </div>

    <div class=" col-lg-4">
        <div class="card border-danger" >
          <div class="card-body">
            <p class="card-text"></p>
            <ul>
              <li class="list-group-item">
                  average:
              </li>
              <li class="list-group-item">
                  range:
              </li>
              <li class="list-group-item">
                  three:
              </li>
              <li class="list-group-item">
                  four:
              </li>
              <li class="list-group-item">
                  five:
              </li>
              <li class="list-group-item">
                  six:
              </li>
              <li class="list-group-item">
                  seven:
              </li>
            </ul>
          </div>
          <div class="card-header text-white text-center bg-info border-info">
            statistics
          </div>
        </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/chart_list.html
{% extends 'base.html' %}
{% block title %}Chart List{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Charts</li>
{% endblock %}

{% block content %}
<h2>{% if request.user.username == username %}My Charts
    {% else %}Charts for {{ username }}
    {% endif %}
</h2>
<hr>
<div class="row container">
    {% for chart in charts %}
        <div class="card border-info mb-3" style="max-width: 20rem;">
          <div class="card-header bg-transparent border-info">
              <h5>{{ chart.name }} DB</h5>
          </div>
          <div class="card-body text-dark">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    From table: {{ chart.table.name }} in DB: {{ chart.table.source_db.DB_name }}
                </li>
                <li class="list-group-item">
                    {{ chart.type|capfirst }} chart
                </li>
                <li class="list-group-item">
                    x-data: {{ chart.column_x }},
                    y-data: {{ chart.column_y }}
                </li>
                <li class="list-group-item">Added on {{ chart.timestamp }}</li>
            </ul>
          </div>
          <div class="card-footer bg-transparent border-info">
              <div class="btn-group" role="group" aria-label="">
                <a role="button" class="btn btn-outline-primary" href="{% url 'dashboard:detail' chart.pk %}">View</a>
                <a role="button" class="btn btn-outline-primary" href="{% url 'dashboard:update' chart.pk %}">Change</a>
                <a role="button" class="btn btn-outline-danger" href="{% url 'dashboard:delete' chart.pk %}">Delete</a>
              </div>
          </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/dashboard/chart_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}Update Chart{% endblock %}

{% block breadcrumb %}
{#    <li class="breadcrumb-item">#}
{#      <a href="{% url 'connection:list' %}">Connection List</a>#}
{#    </li>#}
    <li class="breadcrumb-item active">
      <a href="{% url 'connection:detail' con_pk %}">Connection Detail</a>
    </li>
    <li class="breadcrumb-item active">Update Chart</li>
{% endblock %}


{% block content %}
    <div class="container">
        <form class="form-horizontal col-md-4 offset-md-3" method="post" action="{% url 'dashboard:update' pk %}">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-outline-primary" value="Update">
        </form>
    </div>
{% endblock %}

templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock %}
{% block breadcrumb %}<li class="breadcrumb-item active">My Dashboard</li>{% endblock %}
{% block javascript %}
{#    <script src="{% static "vendor/Chart.js/Chart.bundle.min.js" %}"></script>#}
    <script src="{% static 'node_modules/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'node_modules/@coreui/plugin-chartjs-custom-tooltips/dist/js/custom-tooltips.min.js' %}"></script>
    <script src="{% static "vendors/smoothie/smoothie.js" %}"></script>
    <script src="{% static "vendors/palette.js/palette.js" %}"></script>
    <script src="{% static "channels/js/websocketbridge.js" %}"></script>
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-comments"></i>
          </div>
          <div class="mr-5"><span id="messages">0</span> New Messages!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-warning o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-list"></i>
          </div>
          <div class="mr-5"><span id="tasks">0</span> New Tasks!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-shopping-cart"></i>
          </div>
          <div class="mr-5"><span id="orders">0</span> New Orders!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-support"></i>
          </div>
          <div class="mr-5"><span id="tickets">0</span> New Tickets!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
</div>
 
<div class="row">
    <div class="col-lg-6">
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-line-chart"></i> Chart</div>
        <div class="card-body">
          <canvas id="chart-1" width="100%" ></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-bar-chart"></i> Chart</div>
        <div class="card-body">
          <canvas id="chart-2" width="100%"></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-pie-chart"></i> Chart</div>
        <div class="card-body">
          <canvas id="chart-3" width="365%"></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-bar-chart"></i> Chart
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-sm-8 my-auto">
              <canvas id="chart-4" width="100%" height="50"></canvas>
            </div>
            <div class="col-sm-4 text-center my-auto">
              <div class="h4 mb-0 text-primary">$34,693</div>
              <div class="small text-muted">YTD Revenue</div>
              <hr>
              <div class="h4 mb-0 text-warning">$18,474</div>
              <div class="small text-muted">YTD Expenses</div>
              <hr>
              <div class="h4 mb-0 text-success">$16,219</div>
              <div class="small text-muted">YTD Margin</div>
            </div>
          </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>
</div>
{% endblock %}


{% block extra_javascript %}
   <script src="{% static "js/realtime.js" %}"></script>
{% endblock %}

templates/dashboard/live_chart.html
{% extends "base.html" %}
{% load static %}
{% block title %}Live Chart{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'node_modules/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'node_modules/@coreui/plugin-chartjs-custom-tooltips/dist/js/custom-tooltips.min.js' %}"></script>
    <script src="{% static 'js/live_chart.js' %}"></script>
{% endblock %}

{% block content %}

<div class='row my-5'>
    <div class='col-12'>
        <h1>Live Charts</h1>
    </div>
</div>

<hr/>

<div class='row'>
    <div class="col-md-6">
        <div class="card border-danger" >
          <div class="card-body">
            <canvas class='live-chart' id="chart-1" data-type={{ pk }}  width="400" height="400"></canvas>
          </div>
          <div class="card-footer text-white text-center bg-dark border-danger">
            updated at {{ updated|timesince }}
          </div>
        </div>
    </div>
</div>

<hr>

{% endblock %}