connection/urls.py
from django.urls import path
from django.views.generic import TemplateView
import connection.views as views

app_name = 'connection'

urlpatterns = [
    path('', TemplateView.as_view(template_name='connection/type_select.html'), name='type_select'),
    path('<str:type>/create', views.connection_create, name='create'),
    path('<int:pk>/', views.connection_detail, name='detail'),
    path('<int:pk>/clear', views.tables_clear, name='tables_clear'),
    path('<int:pk>/delete', views.connection_delete, name='delete'),
    path('<int:pk>/update', views.connection_update, name='update'),
    path('table/<int:pk>/', views.loaded_tables, name='loaded_tables'),
    path('table/<int:pk>/add', views.table_add, name='table_add'),
    path('table/<int:pk>/~add', views.table_sql_add, name='table_sql_add'),
    path('table/<int:pk>/detail', views.table_detail, name='table_detail'),
    path('table/<int:pk>/delete', views.table_delete, name='table_delete'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.DashboardView.as_view(), name="home"),
    path('<int:pk>/create', views.chart_create, name='create'),
    path('<int:pk>/delete', views.chart_delete, name='delete'),
    path('<int:pk>/detail', views.chart_detail, name='detail'),
    path('<int:pk>/live', views.live_chart, name='live'),
    path('<int:pk>/update', views.chart_update, name='update'),
    path('<int:con_pk>/list', views.connection_chart_list, name='connection_chart_list'),
    path('<str:username>/list', views.user_chart_list, name='user_chart_list'),
    path('dash', views.Dashboard2View.as_view(), name="dash"),
    path('timeline/', views.TimelineView.as_view(), name="timeline"),
]

datavis/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.views import login
from django.urls import path
from django.views import defaults as default_views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from graphene_django.views import GraphQLView
from users.views import user_home_view


class PrivateGraphQLView(LoginRequiredMixin, GraphQLView):
    pass


urlpatterns = [
    path('', user_home_view, name='user_home'),
    path('home/', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # path('admin/', admin.site.urls),  # set a honeypot on this
    path(settings.ADMIN_URL, admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('connection/', include('connection.urls', namespace='connection')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('package/', include('package.urls', namespace='package')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    url(
        regex=r'^$',
        view=views.user_list_view,
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    # path('<str:username>/charts/', views.UserChartListView.as_view(), name='charts'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from package.models import Package

from .validators import phone_regex


def user_image_path(instance, filename):
    return f'{instance.username}/img/{instance.username}' + '.jpg'


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=False,
                             verbose_name='Phone number', unique=True)
    image = models.ImageField(upload_to=user_image_path, null=True, blank=True)
    # organisation = models.ForeignKey(Organisation, null=True, blank=True, related_name='organisation', on_delete=models.CASCADE)
    # package = models.ForeignKey(Package, null=True, related_name='user', on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    # TODO: take this out later
    @property
    def package(self):
        return self.organisation.package


class Organisation(models.Model):
    TYPE_CHOICES = (
        ('agric', 'Agriculture'),
        ('finance', 'Finance'),
        ('education', 'Education'),
        ('it', 'I.T'),
        ('manufacturing', 'Manufacturing'),
        ('telecom', 'Telecommunication'),
    )
    name = models.CharField(_("Name of organisation"), max_length=255)
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=False,
                             verbose_name='Phone number', unique=True)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    address = models.CharField(max_length=500)
    image = models.ImageField(upload_to=user_image_path, null=True, blank=True)
    users = models.ManyToManyField(User, blank=True)
    package = models.ForeignKey(Package, null=True, related_name='user', on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/forms.py
from django.contrib.auth import get_user_model
from django import forms


class SignupForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('phone', 'image')

    def signup(self, request, user):
        user.phone = self.cleaned_data['phone']
        user.image = self.cleaned_data['image']
        user.save()

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


from connection.models import Connection
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = 'users/detail.html'

    def get_context_data(self, **kwargs):
        # from IPython import embed; embed()
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['cons'] = Connection.objects.filter(user=self.object)
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self, **kwargs):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


# class UserListView(LoginRequiredMixin,  ListView):
#     model = User
#     # These next two lines tell the view to index lookups by username
#     slug_field = 'username'
#     slug_url_kwarg = 'username'


@login_required
def user_list_view(request):
    if request.user.is_staff:
        return render(request, 'users/list.html', {'user_list': User.objects.exclude(is_staff=True)})
    else:
        messages.warning(request, 'Access denied')
        return redirect(request.user)


# class UserChartListView(LoginRequiredMixin, ListView):
#     context_object_name = 'charts'
#     template_name = 'users/user_charts.html'
#
#     slug_field = 'username'
#     slug_url_kwarg = 'username'
#
#     def get_queryset(self):
#         return Chart.objects.filter(table__source_db__user__username=self.kwargs['username'])
#
#     def get_context_data(self, **kwargs):
#         context = super(UserChartListView, self).get_context_data(**kwargs)
#         context['username'] = self.kwargs['username']
#         return context


@login_required
def user_home_view(request):
    return render(request, 'users/detail.html', {"cons": Connection.objects.filter(user=request.user),
                                                 "object": request.user})

templates/users/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<div class="row">
  <div class="col-sm-7">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
    <a class="btn btn-primary" href="{% url 'package:list' %}" role="button">Buy package</a>
    <a class="btn btn-primary" href="{% url 'dashboard:user_chart_list' request.user.username %}" role="button">My Charts</a>
    <a class="btn btn-primary" href="{% url 'connection:type_select' %}" role="button">Add Connections</a>
  </div>
  {% if request.user.is_staff %}
      <div class="col-sm-4">
        <a class="btn btn-success" href="{% url 'users:list' %}" role="button">Users</a>
        <a class="btn btn-success" href="#" role="button">..</a>
      </div>
  {% endif %}
</div>

{% endif %}

<hr>

<div class="row">
    {% for con in cons %}
        <div class="card border-info mb-3" style="max-width: 17rem;">
          <div class="card-header bg-transparent border-info">
              <h5>{{ con.name }} Connection</h5>
          </div>
          <div class="card-body text-dark">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">connected from {{ con.hostname }}</li>
                {% if con.is_valid %}
                    <li class="list-group-item" style="color: blue"> connection validated </li>
                {% else %}
                    <li class="list-group-item" style="color: red"> connection is invalid</li>
                {% endif %}
                    <li class="list-group-item">Added on {{ con.timestamp }}</li>
            </ul>
          </div>
          <div class="card-footer bg-transparent border-info">
              <div class="btn-group" role="group" aria-label="">
                <a role="button" class="btn btn-outline-primary" href="{% url 'connection:detail' con.pk %}">View</a>
                <a role="button" class="btn btn-outline-danger" href="{% url 'connection:delete' con.pk %}">Delete</a>
                <a role="button" class="btn btn-outline-success" href="{% url 'dashboard:connection_chart_list' con.pk %}">Charts</a>
              </div>
          </div>
        </div>
    {% endfor %}
</div>

</div>
{% endblock content %}

templates/users/list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Users{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Users</li>
{% endblock %}

{% block content %}
<div class="container">
    <h2>Customers</h2>
    <hr>

    <div class="list-group col-md-4">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}